sudo: required
language: python
python:
- '3.6'
services:
- docker
addons:
  apt:
    packages:
    - openjdk-8-jdk
before_install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.8.deb
- sudo dpkg -i --force-confnew elasticsearch-5.6.8.deb
- sudo service elasticsearch start
install: pip install -r requirements.txt
before_script:
- sleep 10
- curl -v http://localhost:9200/
script: python -m unittest discover
notifications:
  slack:
    secure: aHNsTacns/t+SVGrX9PeMup4L20Zs/xfHvbQXAt25vNvEv411bH5oydEOTMCoJxQqFENdh2ttrUPbhmcvn4VTvw3EVCb7QXHn2j1RWAWtF000QmdISYiRfd++m1RVhXkI+KqVn5+/xp3O9uKi9jfApXjg8uyewPNnHK1L21XuWi0/ZthoRD7YxX2y/PBD9GmoWNbbtEzIipZt41bcRS+QtynRP8Az9UtbccTU1jCEPHwaM5+3POrhfLuZM1K/0lyYqx4JUmb8MZI4RRgTXtGon49zPjNnnIG1ShgmfmYBBzWaD40VPfq6SVbBpzVcAnEaeQXtwI4E9utuSxkNm3axQ8kXtLwaH1360+RUUmthL4mLVzPSRu22FL7sl4YmpgvuNfzY9VRaHNoBfAZ596y7YVVPTUMCH41vzzeFEqR0O90lCeVjWKHCX3VeXacNtydEwYoxKVbEJBeUjuBjzn/N3iwPJ4BkjxdO4LgAovrDnTb32gc7hUP9cR1P6HlUwd61NRYSnnv5qpvlmIZTh+cUGPX55DjJZVor9Em5kaOlwO3qweIFm7WEYhzD4ncPaY6hENbgSM3p0XBx8B6IKndqczphc3NhLHjvObYya6SMZw2lZelvi3kc6mlxjiLatj2YXPRUGDqg9hjPaBdbMFI7dE6WNJivmnIvJiaCCBvgX0=
deploy:
- provider: script
  script: "./docker_deploy.sh"
  on:
    tags: true
    all_branches: true
- provider: pypi
  user: usc_isi_i2_admin
  server: https://upload.pypi.org/legacy/
  distributions: sdist
  password:
    secure: Geju/mmXjVtl0r6SiSwKo6hWKgmzw1ybMjT/3AUpO/yLnwpVX+KBgTXBwshb86TfTlW1GVeSJ/74mrmHZ3uJY9YIBGN9bHzOs8lTfBLg1q55IiNNrAWDR0MOov03nw+Sn1dPDLzDQQJETfjwUI8cTESXaWmaJaTMm861161q6CkZ77CMySaEGc5HQtO1UOhVUP1Cj8Y5gTSTpTc1mHTfsOctFnkJyXaYx74Q5N7EeWGkSRpXw7Ypc7vyVv/GVDOCRMXM42fgaC0dbLgp8/deJ3yhL+cFVzhLSN1iFh5x8enzw7ep2vUyZm0568NsPaeEWIWNY/GTcibREHUBe8o/cj2+dDKvcPkT5na6NHbp4UKzR7el/CxmFCQ4bKhXVZBkZjm8bB5mV/sw7h3qkXYX/Kv2Jg3Z7Qlo8bbOoNDtX8yHSTHRXvBRkSCgX4y3OFI2pWYPZgFO6ngtncEEZwyvtbDL6V6AtTCecj9vnKdnQelAQmwIvaAHZ0Y/OwVWB00NnInvf/gZe0Eo0W6GeTjsWCHmmacw6RsOXiVEEdCaeu+X0IP8KhEUTCpTwbmOeq9zyr7zXgJbH4KqfSutfiIdoPqf+cABAQqpZYfo/4kKLS1zm4RCj5ekAf7d81LyvbROGWAKuGty+1a0eLv3Y3gLbBMWJRYe3/lunnaq/AmMgBQ=
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: Geju/mmXjVtl0r6SiSwKo6hWKgmzw1ybMjT/3AUpO/yLnwpVX+KBgTXBwshb86TfTlW1GVeSJ/74mrmHZ3uJY9YIBGN9bHzOs8lTfBLg1q55IiNNrAWDR0MOov03nw+Sn1dPDLzDQQJETfjwUI8cTESXaWmaJaTMm861161q6CkZ77CMySaEGc5HQtO1UOhVUP1Cj8Y5gTSTpTc1mHTfsOctFnkJyXaYx74Q5N7EeWGkSRpXw7Ypc7vyVv/GVDOCRMXM42fgaC0dbLgp8/deJ3yhL+cFVzhLSN1iFh5x8enzw7ep2vUyZm0568NsPaeEWIWNY/GTcibREHUBe8o/cj2+dDKvcPkT5na6NHbp4UKzR7el/CxmFCQ4bKhXVZBkZjm8bB5mV/sw7h3qkXYX/Kv2Jg3Z7Qlo8bbOoNDtX8yHSTHRXvBRkSCgX4y3OFI2pWYPZgFO6ngtncEEZwyvtbDL6V6AtTCecj9vnKdnQelAQmwIvaAHZ0Y/OwVWB00NnInvf/gZe0Eo0W6GeTjsWCHmmacw6RsOXiVEEdCaeu+X0IP8KhEUTCpTwbmOeq9zyr7zXgJbH4KqfSutfiIdoPqf+cABAQqpZYfo/4kKLS1zm4RCj5ekAf7d81LyvbROGWAKuGty+1a0eLv3Y3gLbBMWJRYe3/lunnaq/AmMgBQ=
