sudo: required
language: python
python:
- '3.6'
services:
  - docker
addons:
  apt:
    packages:
    - openjdk-8-jdk
before_install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.8.deb
- sudo dpkg -i --force-confnew elasticsearch-5.6.8.deb
- sudo service elasticsearch start
install: pip install -r requirements.txt
before_script:
- sleep 10
- curl -v http://localhost:9200/
script: python -m unittest discover
notifications:
  slack:
    secure: aHNsTacns/t+SVGrX9PeMup4L20Zs/xfHvbQXAt25vNvEv411bH5oydEOTMCoJxQqFENdh2ttrUPbhmcvn4VTvw3EVCb7QXHn2j1RWAWtF000QmdISYiRfd++m1RVhXkI+KqVn5+/xp3O9uKi9jfApXjg8uyewPNnHK1L21XuWi0/ZthoRD7YxX2y/PBD9GmoWNbbtEzIipZt41bcRS+QtynRP8Az9UtbccTU1jCEPHwaM5+3POrhfLuZM1K/0lyYqx4JUmb8MZI4RRgTXtGon49zPjNnnIG1ShgmfmYBBzWaD40VPfq6SVbBpzVcAnEaeQXtwI4E9utuSxkNm3axQ8kXtLwaH1360+RUUmthL4mLVzPSRu22FL7sl4YmpgvuNfzY9VRaHNoBfAZ596y7YVVPTUMCH41vzzeFEqR0O90lCeVjWKHCX3VeXacNtydEwYoxKVbEJBeUjuBjzn/N3iwPJ4BkjxdO4LgAovrDnTb32gc7hUP9cR1P6HlUwd61NRYSnnv5qpvlmIZTh+cUGPX55DjJZVor9Em5kaOlwO3qweIFm7WEYhzD4ncPaY6hENbgSM3p0XBx8B6IKndqczphc3NhLHjvObYya6SMZw2lZelvi3kc6mlxjiLatj2YXPRUGDqg9hjPaBdbMFI7dE6WNJivmnIvJiaCCBvgX0=

deploy:
- provider: pypi
  user: digsandpaper
  server: https://upload.pypi.org/legacy/
  distributions: sdist
  password:
    secure: "HeqXMGPzfgD4UyRIwT3VuU8uQQ01bjGepdaK5DNTUToLwFc8eAMz32SmO7G0DLl+yQYvlHeTK3bup/bOyPTbK6UOqscXI9LPLv22NqhJB/p19hHTG6B3VO3mBxFsFliKez3E4hgXtY3D/gc2CJuu+vjdZhjQ4pqlvWMY+P4y1hq5hJdx1Ad2qxufDxVVpTadfUXFn5igHVY5tqNCM8o7XqeM2Vm5E8l8bPdbneOn85vlKC+Mb0WlG+5YyBqk8i5Y8kiURlYtX+/XsGx0YRxnXgt6jH8oA921Sv3FThl7VjDhM/OnRfUxOKOoUJQBLvmxcsK6NF+TgBBaVT35DVaNciybf2aW5tkR0C4fjZGNREmfifvGEMsM/GTTItic4KtC9uat2qz1qmOK0qEUlNnf2bRnBvqaJJdPc2Ah4VkhiLkmf+1ZkHZcEUyoB134jfKMD2GQHEECt4B8y/tdwyYX8o7RO05WKFzn6mNZOlkrneiZgJ3/ebObQNydtP6+nN+KqjVaZFKmxK3BD93jb3FODxQEozk7lM6EFomhR8gknaFLbKghb/c1Wd1Fz+jnUIc+3ZHU3mibPxyztoNfYZOIGTjZ6grx75yyUgL4xmrgAyorF9T2Vc9PoEaPohZheRy/J+Rcdf/QkO2iWhAr3DJoyUpykAIVszzfrQgco+YBBug="
  on:
    tags: true
    all_branches: true
- provider: script
  script: ./docker_deploy.sh
  on:
    tags: true
    all_branches: true
