sudo: required
language: python
python:
- '2.7'
services:
  - docker
addons:
  apt:
    packages:
    - oracle-java8-set-default
before_install:
- curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.1/elasticsearch-2.4.1.deb
- sudo dpkg -i --force-confnew elasticsearch-2.4.1.deb
- sudo service elasticsearch start
install: pip install -r requirements.txt
before_script:
- sleep 10
- curl -v http://localhost:9200/
script: python -m unittest discover
notifications:
  slack:
    secure: aHNsTacns/t+SVGrX9PeMup4L20Zs/xfHvbQXAt25vNvEv411bH5oydEOTMCoJxQqFENdh2ttrUPbhmcvn4VTvw3EVCb7QXHn2j1RWAWtF000QmdISYiRfd++m1RVhXkI+KqVn5+/xp3O9uKi9jfApXjg8uyewPNnHK1L21XuWi0/ZthoRD7YxX2y/PBD9GmoWNbbtEzIipZt41bcRS+QtynRP8Az9UtbccTU1jCEPHwaM5+3POrhfLuZM1K/0lyYqx4JUmb8MZI4RRgTXtGon49zPjNnnIG1ShgmfmYBBzWaD40VPfq6SVbBpzVcAnEaeQXtwI4E9utuSxkNm3axQ8kXtLwaH1360+RUUmthL4mLVzPSRu22FL7sl4YmpgvuNfzY9VRaHNoBfAZ596y7YVVPTUMCH41vzzeFEqR0O90lCeVjWKHCX3VeXacNtydEwYoxKVbEJBeUjuBjzn/N3iwPJ4BkjxdO4LgAovrDnTb32gc7hUP9cR1P6HlUwd61NRYSnnv5qpvlmIZTh+cUGPX55DjJZVor9Em5kaOlwO3qweIFm7WEYhzD4ncPaY6hENbgSM3p0XBx8B6IKndqczphc3NhLHjvObYya6SMZw2lZelvi3kc6mlxjiLatj2YXPRUGDqg9hjPaBdbMFI7dE6WNJivmnIvJiaCCBvgX0=
env:
  global:
  - secure: bOXx3dVac0Boy9oo6OMfxNNXUJnpJL2xg1zP+RRpbodJGd+TOWA4MlV9JuabCajOHN/Mo8pR29biis3KFoWreZ+Fj5fVKsOo3o0E8HIAAdXpbx3TVCJSHZE7g29s2moz/bgEXt8Hr1LRgDKWjC5eoJnqBZJGuyCfbA5Cc9kAdlOZZ3NUyMoswSYx9QGOjd85D+4bVHSImWDp69lxXVCShVx5vhigocO1XetESgGV/dsMinkM8GaBXzg4IKsC/Zc3j0LHbmdqIGrxlSJEhHiGKIWcQDMU8QcNIAkEdCbbVFzCmsKll7+GnExxPyUX4DjY2FKwSZM2L2pO2rLRWV7HWlv8LV0jpTW1qHCmKVCwH4CLJO8W5ZDmjK7/kr8SuGpCBIGTL6p3KF0E3mSBAyM8rqg9lTmgDRSxtldqIi4qrMiyGCt2pAjo8+JAKEoEQC7BdeLHpgcCFPTRGo8Y67k+rBHQAegEtB9KhoYMT+yPy4EEVGejQyOF0CvohShdxBqn1X9rL4fA8y73xh6ckwLmSDEHq1Cv9Lj1zjf8uV2tmZ7UHucgKiA02HBlD4gLNXvEchhJjn+AXO8lPEWtUioNhM5BeMJpcj5OkhRfqE2HanOrWybGEiU3t4r+kNf1yh9c4HNKx3r2J5w2XIA6yf5ra/AofVTNSIlNxFTZXeofpzM=
  - secure: P12RvF/BNs7PjRqn9TCT5QONd5teogxD5VO8UxSj4SRPtTZoYld2JxkRzctGj2P6cwJFj9RDpuwDSt84WYf2Q6jwqmCSRUfLkHwoxpmAZtYfTRm1mUlnkRriP/qwGQK6QHkDN2FbJo9WD49bBqK4Kyxbq/ObzAaG1boxho15FqQKRlNd0jTmJHk3V/CCzHpnI+1RzNxZN3+KVaxlYTwD209H+EIinXg1l49fMbM/gdAFI81odSEfVJoYbm6QQQdT4vRvLUfs1kSzfjtQFpMV9qGWPMR7Ujx9V9un8mXSlPKvNfUi6O4MZ2ZqfgytF4ONkaAXm0DKO9eTt0vTik9GNtS6EMqQdZqAZyyviBAJllNrFQ7M19o6r+FT0sGVsk5iHblyTjCK6zX096/LsnpmXbzLYLTqKPHk6ZZ50vL9rR52nYqdEAuPzCPJwOCPQTWrx3XlLAHc8dOOVSBwYeSwnkWcgbi95qzuwMiouxGtxbosSsuMlxEakPgHSN+OySr7pUILPdzbVXpf7dzz1toPT75dopqLYUNEnM/yT+lGhE4Tf7ZN36eblIBFxJujQVCrVbnFDpJfXSa2TNaoovmFBEBjPKtxRsQtaO7pLQJIeBL6ykTw/KfYIkB16aIjGmsULgqY/P57NNwbQPftAHjo+/RrIQW41+eKWR9xC1+9wnA=
  - secure: tmgiREbl5QWKNLP3p3/QcA07hx2KdJeJN0hpfkYzOkZRHgr3nox+yV/tH09k4GvLfj222x2iFXUMwo0u+Dsm9C85BT24zgVltiZmlYxZ1uQ7hcMrErARayD7Bob8mf0BglFGVyl6v+xAoDDO5YnxXFQlmAt0ArKBP0yyYRwSlW4DdHGdgJgHiri3Ie5SCW3rI6wDZ9tBTHsBAr+SGPsuRFivG9sy36Wgk0OPVts1aSjUW2U/HNlz/MFKYDWQzs8urk4kYO1++XyOI1YRMFO0XoQUwH25aMHGsNsn/Jwos13XLFirueNeUo6qzopC4acwkrsXuU/68no8V1PyA6pQ18KCtEiw7IldDvepZJQJnIQB75L9k6v/vcnL8MsewxGfOzieJt7TStxqd/5BOvYkjgGTbqQfFYK6opf3qAq0JH3uCYP/eWqU+Sz9h6mi6gOKA+tKTqW1ZlWTv7k5DQTEvNS2XPuQvoga3SzVL6N4BNJCyIVU2TERouPCyVjmwuG8MthNN8C1geo1uAToTtzcOm/l9MYf66vB1Ynkl3PZD0k5J8UMRtnxwLdEYqQRUnG2IF0YLZUubKGwCHadtg7/TKV1VilO6AgyAv3PypcWJGffq2YsE8+9ex2ukYn6g1Ohs7NMn5ySAmmB2KZQXLF35FTnK45z6PB5W39cF3ynu+4=
deploy:
- provider: pypi
  user: digsandpaper
  password:
    secure: "PKsjgBiX2h4rLsdCoG5iP3KOdQJRbjGKBhfLijP9d9f1EuDsf6XAT/DPslBX5gJ0pYytI5kLbFwWkVrj8L/fB1N2WoCDtXhKGqIQP2AWAyiyXXamjWED1MfskS9wYsODxRV08dtg3SBwNi/dAb1xIUFVbmwSWvtaQeksK42fFgZM3EDqbLqXa1c3gyTKH1CPAmoML3lKvLSlvwtYPFvQUvYojYC1kx2r45QvPHjD9BGDWM3nBbOEuj0x3g/zrZYTNBRMt30C9t41lFBgcVpNODGbyS9Otcww8E/FkHiypGSkTBPDOYLVQY+xBbWIqDXdtXyRWi8TBbJXwGoUi393ykhbb1JvVtTX1eQ55D+lbVp9T3jpKbMHu7cood1dd+A6ChdHtvpPQ9AzljLAE4Vm47g7OKOiX5WHjKG58sHFlASSjDir72Qd+GaFAiR+po6OOqEFhsGLgjbw5iObY2+6JO9Zs4zR664o4v4EtJGVF8T4h4CScLUFXhQ7EybeTO6/WAtbZEuG+M2zurgx7fBe8rO/Nzl/nAaOyBpJhLTDVSfc1ub2PfpDcOkMZg15wCQQNtY3aHAu3YdLEvl2hbwaJAE3DFsDcE9lJk7uz7josVCj2Bj9jkAlPrV1itrmB5flIcPlAaz6t9KoaO/Y6IuiP2JxAlWWgLryQ1PnHTsAJG4="
  on:
    tags: true
    all_branches: true
- provider: script
  script: docker_deploy.sh
  on:
    tags: true
    all_branches: true
